// ignore_for_file: constant_identifier_names

/// All ISO 4217 currencies with code, name, and symbol.
/// Symbol falls back to the code if no dedicated symbol exists.
class CurrencyData {
  final String code;
  final String name;
  final String symbol;

  const CurrencyData({
    required this.code,
    required this.name,
    required this.symbol,
  });

  @override
  String toString() => '$symbol  $code — $name';
}

const List<CurrencyData> allCurrencies = [
  CurrencyData(code: 'AED', name: 'UAE Dirham', symbol: 'د.إ'),
  CurrencyData(code: 'AFN', name: 'Afghan Afghani', symbol: '؋'),
  CurrencyData(code: 'ALL', name: 'Albanian Lek', symbol: 'L'),
  CurrencyData(code: 'AMD', name: 'Armenian Dram', symbol: '֏'),
  CurrencyData(code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ'),
  CurrencyData(code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz'),
  CurrencyData(code: 'ARS', name: 'Argentine Peso', symbol: '\$'),
  CurrencyData(code: 'AUD', name: 'Australian Dollar', symbol: 'A\$'),
  CurrencyData(code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ'),
  CurrencyData(code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼'),
  CurrencyData(code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM'),
  CurrencyData(code: 'BBD', name: 'Barbadian Dollar', symbol: 'Bds\$'),
  CurrencyData(code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳'),
  CurrencyData(code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв'),
  CurrencyData(code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب'),
  CurrencyData(code: 'BIF', name: 'Burundian Franc', symbol: 'Fr'),
  CurrencyData(code: 'BMD', name: 'Bermudan Dollar', symbol: 'BD\$'),
  CurrencyData(code: 'BND', name: 'Brunei Dollar', symbol: 'B\$'),
  CurrencyData(code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.'),
  CurrencyData(code: 'BRL', name: 'Brazilian Real', symbol: 'R\$'),
  CurrencyData(code: 'BSD', name: 'Bahamian Dollar', symbol: 'B\$'),
  CurrencyData(code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu'),
  CurrencyData(code: 'BWP', name: 'Botswanan Pula', symbol: 'P'),
  CurrencyData(code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br'),
  CurrencyData(code: 'BZD', name: 'Belize Dollar', symbol: 'BZ\$'),
  CurrencyData(code: 'CAD', name: 'Canadian Dollar', symbol: 'CA\$'),
  CurrencyData(code: 'CDF', name: 'Congolese Franc', symbol: 'Fr'),
  CurrencyData(code: 'CHF', name: 'Swiss Franc', symbol: 'Fr'),
  CurrencyData(code: 'CLP', name: 'Chilean Peso', symbol: 'CLP\$'),
  CurrencyData(code: 'CNY', name: 'Chinese Yuan', symbol: '¥'),
  CurrencyData(code: 'COP', name: 'Colombian Peso', symbol: 'COL\$'),
  CurrencyData(code: 'CRC', name: 'Costa Rican Colón', symbol: '₡'),
  CurrencyData(code: 'CUP', name: 'Cuban Peso', symbol: '\$MN'),
  CurrencyData(code: 'CVE', name: 'Cape Verdean Escudo', symbol: '\$'),
  CurrencyData(code: 'CZK', name: 'Czech Koruna', symbol: 'Kč'),
  CurrencyData(code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj'),
  CurrencyData(code: 'DKK', name: 'Danish Krone', symbol: 'kr'),
  CurrencyData(code: 'DOP', name: 'Dominican Peso', symbol: 'RD\$'),
  CurrencyData(code: 'DZD', name: 'Algerian Dinar', symbol: 'دج'),
  CurrencyData(code: 'EGP', name: 'Egyptian Pound', symbol: 'E£'),
  CurrencyData(code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk'),
  CurrencyData(code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br'),
  CurrencyData(code: 'EUR', name: 'Euro', symbol: '€'),
  CurrencyData(code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ\$'),
  CurrencyData(code: 'FKP', name: 'Falkland Islands Pound', symbol: 'FK£'),
  CurrencyData(code: 'GBP', name: 'British Pound', symbol: '£'),
  CurrencyData(code: 'GEL', name: 'Georgian Lari', symbol: '₾'),
  CurrencyData(code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵'),
  CurrencyData(code: 'GIP', name: 'Gibraltar Pound', symbol: '£'),
  CurrencyData(code: 'GMD', name: 'Gambian Dalasi', symbol: 'D'),
  CurrencyData(code: 'GNF', name: 'Guinean Franc', symbol: 'Fr'),
  CurrencyData(code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q'),
  CurrencyData(code: 'GYD', name: 'Guyanaese Dollar', symbol: 'G\$'),
  CurrencyData(code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK\$'),
  CurrencyData(code: 'HNL', name: 'Honduran Lempira', symbol: 'L'),
  CurrencyData(code: 'HRK', name: 'Croatian Kuna', symbol: 'kn'),
  CurrencyData(code: 'HTG', name: 'Haitian Gourde', symbol: 'G'),
  CurrencyData(code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft'),
  CurrencyData(code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp'),
  CurrencyData(code: 'ILS', name: 'Israeli New Shequel', symbol: '₪'),
  CurrencyData(code: 'INR', name: 'Indian Rupee', symbol: '₹'),
  CurrencyData(code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د'),
  CurrencyData(code: 'IRR', name: 'Iranian Rial', symbol: '﷼'),
  CurrencyData(code: 'ISK', name: 'Icelandic Króna', symbol: 'kr'),
  CurrencyData(code: 'JMD', name: 'Jamaican Dollar', symbol: 'J\$'),
  CurrencyData(code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD'),
  CurrencyData(code: 'JPY', name: 'Japanese Yen', symbol: '¥'),
  CurrencyData(code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh'),
  CurrencyData(code: 'KGS', name: 'Kyrgystani Som', symbol: 'лв'),
  CurrencyData(code: 'KHR', name: 'Cambodian Riel', symbol: '៛'),
  CurrencyData(code: 'KMF', name: 'Comorian Franc', symbol: 'Fr'),
  CurrencyData(code: 'KPW', name: 'North Korean Won', symbol: '₩'),
  CurrencyData(code: 'KRW', name: 'South Korean Won', symbol: '₩'),
  CurrencyData(code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KD'),
  CurrencyData(code: 'KYD', name: 'Cayman Islands Dollar', symbol: 'CI\$'),
  CurrencyData(code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸'),
  CurrencyData(code: 'LAK', name: 'Laotian Kip', symbol: '₭'),
  CurrencyData(code: 'LBP', name: 'Lebanese Pound', symbol: 'LL'),
  CurrencyData(code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨'),
  CurrencyData(code: 'LRD', name: 'Liberian Dollar', symbol: 'L\$'),
  CurrencyData(code: 'LSL', name: 'Lesotho Loti', symbol: 'L'),
  CurrencyData(code: 'LYD', name: 'Libyan Dinar', symbol: 'LD'),
  CurrencyData(code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD'),
  CurrencyData(code: 'MDL', name: 'Moldovan Leu', symbol: 'L'),
  CurrencyData(code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar'),
  CurrencyData(code: 'MKD', name: 'Macedonian Denar', symbol: 'ден'),
  CurrencyData(code: 'MMK', name: 'Myanmar Kyat', symbol: 'K'),
  CurrencyData(code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮'),
  CurrencyData(code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP\$'),
  CurrencyData(code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM'),
  CurrencyData(code: 'MUR', name: 'Mauritian Rupee', symbol: '₨'),
  CurrencyData(code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf'),
  CurrencyData(code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK'),
  CurrencyData(code: 'MXN', name: 'Mexican Peso', symbol: 'MX\$'),
  CurrencyData(code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM'),
  CurrencyData(code: 'MZN', name: 'Mozambican Metical', symbol: 'MT'),
  CurrencyData(code: 'NAD', name: 'Namibian Dollar', symbol: 'N\$'),
  CurrencyData(code: 'NGN', name: 'Nigerian Naira', symbol: '₦'),
  CurrencyData(code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C\$'),
  CurrencyData(code: 'NOK', name: 'Norwegian Krone', symbol: 'kr'),
  CurrencyData(code: 'NPR', name: 'Nepalese Rupee', symbol: '₨'),
  CurrencyData(code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ\$'),
  CurrencyData(code: 'OMR', name: 'Omani Rial', symbol: 'OMR'),
  CurrencyData(code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.'),
  CurrencyData(code: 'PEN', name: 'Peruvian Sol', symbol: 'S/.'),
  CurrencyData(code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K'),
  CurrencyData(code: 'PHP', name: 'Philippine Peso', symbol: '₱'),
  CurrencyData(code: 'PKR', name: 'Pakistani Rupee', symbol: '₨'),
  CurrencyData(code: 'PLN', name: 'Polish Zloty', symbol: 'zł'),
  CurrencyData(code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲'),
  CurrencyData(code: 'QAR', name: 'Qatari Rial', symbol: 'QR'),
  CurrencyData(code: 'RON', name: 'Romanian Leu', symbol: 'lei'),
  CurrencyData(code: 'RSD', name: 'Serbian Dinar', symbol: 'din'),
  CurrencyData(code: 'RUB', name: 'Russian Ruble', symbol: '₽'),
  CurrencyData(code: 'RWF', name: 'Rwandan Franc', symbol: 'Fr'),
  CurrencyData(code: 'SAR', name: 'Saudi Riyal', symbol: '﷼'),
  CurrencyData(code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI\$'),
  CurrencyData(code: 'SCR', name: 'Seychellois Rupee', symbol: '₨'),
  CurrencyData(code: 'SDG', name: 'Sudanese Pound', symbol: 'LS'),
  CurrencyData(code: 'SEK', name: 'Swedish Krona', symbol: 'kr'),
  CurrencyData(code: 'SGD', name: 'Singapore Dollar', symbol: 'S\$'),
  CurrencyData(code: 'SHP', name: 'St. Helena Pound', symbol: '£'),
  CurrencyData(code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le'),
  CurrencyData(code: 'SOS', name: 'Somali Shilling', symbol: 'Sh'),
  CurrencyData(code: 'SRD', name: 'Surinamese Dollar', symbol: 'Sr\$'),
  CurrencyData(code: 'STN', name: 'São Tomé & Príncipe Dobra', symbol: 'Db'),
  CurrencyData(code: 'SVC', name: 'Salvadoran Colón', symbol: '₡'),
  CurrencyData(code: 'SYP', name: 'Syrian Pound', symbol: 'LS'),
  CurrencyData(code: 'SZL', name: 'Swazi Lilangeni', symbol: 'L'),
  CurrencyData(code: 'THB', name: 'Thai Baht', symbol: '฿'),
  CurrencyData(code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM'),
  CurrencyData(code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T'),
  CurrencyData(code: 'TND', name: 'Tunisian Dinar', symbol: 'DT'),
  CurrencyData(code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T\$'),
  CurrencyData(code: 'TRY', name: 'Turkish Lira', symbol: '₺'),
  CurrencyData(code: 'TTD', name: 'Trinidad & Tobago Dollar', symbol: 'TT\$'),
  CurrencyData(code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT\$'),
  CurrencyData(code: 'TZS', name: 'Tanzanian Shilling', symbol: 'Sh'),
  CurrencyData(code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴'),
  CurrencyData(code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh'),
  CurrencyData(code: 'USD', name: 'US Dollar', symbol: '\$'),
  CurrencyData(code: 'UYU', name: 'Uruguayan Peso', symbol: '\$U'),
  CurrencyData(code: 'UZS', name: 'Uzbekistani Som', symbol: 'лв'),
  CurrencyData(code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs.S'),
  CurrencyData(code: 'VND', name: 'Vietnamese Dong', symbol: '₫'),
  CurrencyData(code: 'VUV', name: 'Vanuatu Vatu', symbol: 'Vt'),
  CurrencyData(code: 'WST', name: 'Samoan Tala', symbol: 'T'),
  CurrencyData(code: 'XAF', name: 'Central African CFA Franc', symbol: 'Fr'),
  CurrencyData(code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC\$'),
  CurrencyData(code: 'XOF', name: 'West African CFA Franc', symbol: 'Fr'),
  CurrencyData(code: 'XPF', name: 'CFP Franc', symbol: 'Fr'),
  CurrencyData(code: 'YER', name: 'Yemeni Rial', symbol: '﷼'),
  CurrencyData(code: 'ZAR', name: 'South African Rand', symbol: 'R'),
  CurrencyData(code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK'),
  CurrencyData(code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'Z\$'),
];

/// Look up a [CurrencyData] by its code. Returns INR if not found.
CurrencyData currencyByCode(String code) {
  return allCurrencies.firstWhere(
    (c) => c.code == code,
    orElse: () =>
        const CurrencyData(code: 'INR', name: 'Indian Rupee', symbol: '₹'),
  );
}
